server:
  port: 28889
  servlet:
    context-path:  /
spring:
  datasource:
    username: dark
    password: dark123
    url: jdbc:mysql://120.77.149.78:3307/dark?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
