server:
  port: 28889
  servlet:
    context-path:  /
spring:
  datasource:
    username: ${MYSQL_UserName:dark}
    password: ${MYSQL_PassWord:dark123}
    url: jdbc:mysql://${HOST:120.77.149.78}:${MYSQL_PORT:3307}/${MYSQL_DBNAME:dark}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    database: 0
    host: ${HOST:120.77.149.78}
    port: 6379
    password: ${REDIS_PWD:redis123}
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    connect-timeout: 1000

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
pagehelper:
  helperDialect: MYSQL
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.example: info
    cn.jay.repository: trace
jwt:
  header: Authorization
  # 令牌前缀
  bearer: Bearer
  # 使用Base64对该令牌进行编码
  secret: 3ce47fcc969a4cffa29e298d8f83134eabcdefghijklmn
  expireTime: 300

